spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY:test}
        secret-key: ${AWS_SECRET_KEY:test}
        session: ${AWS_SESSION_TOKEN:test}
      region:
        static: ${AWS_REGION:us-east-1}
      s3:
        endpoint: ${S3_URL:http://s3.localhost.localstack.cloud:4567/}
      sqs:
        endpoint: ${SQS_URL:http://localhost:4567}
        queues:
          processamento-realizado: processamento-realizado
          processa-video: processa-video
          erro-processamento: erro-processamento
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

amazon:
  s3:
    bucket: hackaton-tech-challenge-videos-ld

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  server:
    servlet:
      context-path: /actuator