services:
  localstack-processa-video:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-processa-video}"
    image: localstack/localstack
    ports:
      - "4568:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=sqs,s3,sns
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:4568
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-aws:/etc/localstack/init/ready.d"

  app-recebimento-video:
    build:
      context: ..
      dockerfile: ./Dockerfile
    container_name: spring-boot-app-processa-video
    ports:
      - "8082:8080"
    depends_on:
      - localstack-processa-video
    networks:
      - backend

networks:
  backend: