apiVersion: apps/v1
kind: Deployment
metadata:
  name: processa-video-app
  namespace: hackathon-fiap
  labels:
    app.kubernetes.io/name: processa-video-app
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: processa-video-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: processa-video-app
    spec:
      serviceAccountName: processa-video-serviceaccount
      containers:
        - name: processa-video-app
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "1024m"
              memory: "2048M"
            limits:
              cpu: "2048m"
              memory: "4096M"
          env:
            - name: S3_URL
              valueFrom:
                configMapKeyRef:
                  name: processa-video-configmap
                  key: s3_url
            - name: SQS_URL
              valueFrom:
                configMapKeyRef:
                  name: processa-video-configmap
                  key: sqs_url
            - name: AWS_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: processa-video-configmap
                  key: aws_secret_key
            - name: AWS_SESSION_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: processa-video-configmap
                  key: aws_session_token
            - name: AWS_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: processa-video-configmap
                  key: aws_access_key
          ports:
            - name: http-port
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http-port
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http-port
            initialDelaySeconds: 240
            periodSeconds: 15
            failureThreshold: 3